name: Latest blog post workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://feeds.feedburner.com/belajarstatistics?format=xml,https://feeds.feedburner.com/belajarstatistik?format=xml"
          max_post_count: 5
